### ISSUE TITLE
[1.12] Missing Textures

### ISSUE THREAD

**Issue by TheLimePixel** [bence98/SodiumCraft#1]
All the items from the mod have missing textures:
![image](https://user-images.githubusercontent.com/25333164/30251448-9af0b440-965f-11e7-8ec5-ce4bec8e594b.png)

**Comment by bence98** [comment]
You didn't write which version of the mod you're using, but I'm guessing by the screenshot it is MC 1.12.1, SodiumCraft 1.2.1. Which Forge version?

**Comment by TheLimePixel** [comment]
14.22.0.2474
You should set a base for the information you need then.

**Comment by bence98** [comment]
Please try SodiumCraft 1.3.1. It should be available soon on Curse

**Comment by TheLimePixel** [comment]
Yup, it works!
