### ISSUE TITLE
Incompatible with Mekanism 1.12.2-9.4.3.330

### ISSUE THREAD

**Issue by Xiaminou** [bence98/SodiumCraft#2]
Incompatible with Mekanism 1.12.2-9.4.3.330

**Comment by jkroepke** [comment]
See: https://github.com/aidancbrady/Mekanism/issues/4877

**Comment by bence98** [comment]
SodiumCraft 1.3.2 should fix it. Side-effect is that now it will not work with older Mekanism versions :/
